<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0x8ktkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0x8ktkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0x8ktkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0x8ktkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0x8ktkx\App_KernelDevDebugContainer([
    'container.build_hash' => '0x8ktkx',
    'container.build_id' => 'c14c8640',
    'container.build_time' => 1596400442,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0x8ktkx');
