<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTCsoY9s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTCsoY9s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTCsoY9s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTCsoY9s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTCsoY9s\App_KernelDevDebugContainer([
    'container.build_hash' => 'TCsoY9s',
    'container.build_id' => 'd09300d5',
    'container.build_time' => 1596360746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTCsoY9s');
